### ISSUE TITLE
Can you update to the latest modified version?

### ISSUE THREAD

**Issue by icyfox168168** [FAETHER/tinycc#2]
Can you update to the latest modified version?

**Comment by kyx0r** [comment]
Yes I can, but keep in mind that the latest version of tcc is a bit more bloated, as Danny added support for extended asm for arm. This is a special version cause I almaginated it manually, using my own almagination tool right now will blow it up to 80K LOC ++ because of the macro expansion, the tokens witll be dublicated per architecture.

**Comment by kyx0r** [comment]
Also there were done some major changes in tcc in the last 2 years concerning __va_args and some intrinsics. Basically updating it is bit more work even with the help of my program.

**Comment by icyfox168168** [comment]
Yes, the workload is very large. It would be better if it can be updated. The single-file version is really convenient. Thank you for making this version, but there are some tcc bugs.

**Comment by kyx0r** [comment]
Ok, I'll give it a look. I will place updated version on a separate branch as it would probably need some more manual changes done and testing before it becomes usable. I am currently working on my own x86_x64 compiler for c99, (smaller and better than tcc) so if you be willing to maintain (or at least find and report bugs) the updated version moving forward that'd be great.

**Comment by icyfox168168** [comment]
When will your compiler be released? It is a wonderful thing if your tcc is better. There is a bug in the tcc linker that has not been fixed. When the image address is greater than 32 bits, some codes will have pointer errors.

**Comment by icyfox168168** [comment]
I found a lot of bugs for this c compiler, how does your compiler compare with this

https://github.com/lasarus/C-Compiler/issues/1

**Comment by icyfox168168** [comment]
tcc build bddisasm

when -Wl,-image-base=0x140000000    

run point error

**Comment by kyx0r** [comment]
My compiler is still pretty far from usable, planing to release a prototype by 2022. But it's hard to say exactly, my goal is to write the fastest & smallest code possible. I take references from tcc, neatcc, and chibicc so it'll be a mix of things from all over the place.

**Comment by icyfox168168** [comment]
Is the architecture the same as tcc?

**Comment by icyfox168168** [comment]
Come on, look forward to your compiler, tcc single file modified version is not needed, waste time, you have your own compiler plan

**Comment by kyx0r** [comment]
So you don't need the amalgamation tcc version anymore? My compiler is cool, but inevitably it is still maybe a year or 2 of development time away to be fully c99 compliant. The architecture will be multi pass compiler, however I care about compilation speed, so it's not going to have a lot of fancy codegen optimizations being done at first, but it should be capable in theory of good code gen if someone wants to implement the algorithms for it. Right now x86_64 linux is the only target, possibly in the future win32/64 will get added as separate branch, everything in compiler will be modular, like extra arch support, or feature, etc will be separate so that there is none of that #ifdef mess.

**Comment by icyfox168168** [comment]
Watching you describe your compiler is really cool and can't wait to test it

**Comment by icyfox168168** [comment]
If you have time, you can make the latest single file version. Thank you very much

**Comment by icyfox168168** [comment]
It is best to use this version to modify

http://repo.or.cz/tinycc.git

**Comment by icyfox168168** [comment]
Now V language uses TCC as the back-end compiler. All your compilers can use the examples of V language, which is a very good test method

**Comment by icyfox168168** [comment]
Will your compiler have TCC's unique ability to compile code into memory?

**Comment by kyx0r** [comment]
1. Compiling code into memory is a very cool feature. I would probably consider it.
2. I have updated the source, see branch https://github.com/kyx0r/tinycc/tree/1645616
I compiles fine under linux with gcc, but it obviously needs a lot more work to get it into
a reasonable looking state. The result is 100K LOC, if worked on it can be get down
to probably 70K LOC. But yeah as you can see the tcc has gotten quite a bit more fat
over the last years, which is why I don't particularly like it anymore.

**Comment by kyx0r** [comment]
Also see the readme on that branch; the almaga program creates blank new lines in the source code sometimes, it can be cleaned up with some code formatting tool, like astyle for example.

**Comment by icyfox168168** [comment]
Compile -m64 failed on win10

Compile  -m32 ok

gcc tinycc.c  -DTCC_TARGET_PE -DTCC_TARGET_X86_64 -o tcc.exe -static -O2 -fvisibility=hidden -s
In file included from C:/TDM-GCC-64/x86_64-w64-mingw32/include/winnt.h:27,
                 from C:/TDM-GCC-64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/TDM-GCC-64/x86_64-w64-mingw32/include/windef.h:9,
                 from C:/TDM-GCC-64/x86_64-w64-mingw32/include/windows.h:69,
                 from tinycc.c:884:
C:/TDM-GCC-64/x86_64-w64-mingw32/include/psdk_inc/intrin-impl.h:616:6: error: redefinition of '__faststorefence'
  616 | void __faststorefence(void) {
      |      ^~~~~~~~~~~~~~~~
C:/TDM-GCC-64/x86_64-w64-mingw32/include/psdk_inc/intrin-impl.h:613:6: note: previous definition of '__faststorefence' was here
  613 | void __faststorefence(void);
      |      ^~~~~~~~~~~~~~~~
tinycc.c: In function 'win64_add_function_table':
tinycc.c:63722:38: error: expected ')' before 'sizeof'
63722 |             s1->uw_pdata->data_offset  sizeof (RUNTIME_FUNCTION),
      |                                      ^ ~~~~~~
      |                                      )
tinycc.c:63720:9: error: too few arguments to function 'RtlAddFunctionTable'
63720 |         RtlAddFunctionTable(

**Comment by icyfox168168** [comment]
This code compilation error, the latest version of tcc should be fixed

test.c:8: error: incompatible types for redefinition of 'arr'

#include <windows.h> /*or on unix*/ #include <stdlib.h>

#include <assert.h>

#define SIZE 10

extern int arr[SIZE];
int arr[] = { 11, 34, };

int test() {
	assert(sizeof arr == SIZE * sizeof (int));
	return 0;
}


//This declaration is required to make printf external.
int printf(char *format, ...);

//See tinycc.c on how to do argc and argv
int _start()
{
        test();
	printf("Hello World\n"); //crt is usable
	return 1;
}

**Comment by icyfox168168** [comment]
Have time to update the error raised above?

**Comment by kyx0r** [comment]
Feel free to create pull request, or send a .diff/.patch. Currently I don't have any computer with win64 on it to test, hopefully that error is simple enough to fix. I am quite busy tomorrow so, maybe I'll give it some more attention next week, out of curiosity.
